jobs:
  python3.6:
    docker:
      - image: circleci/python:3.6.9
    steps:
      - checkout
      - run:
          name: Python 3.6.9 CLI Test
          command: |
            python3 -V
            bash ./testing-run.sh
            bash ./regenerate-names.sh
  python3.7:
    docker:
      - image: circleci/python:3.7.7
    steps:
      - checkout
      - run:
          name: Python 3.7.7 CLI Test
          command: |
            python3 -V
            bash ./testing-run.sh
            bash ./regenerate-names.sh
  python3.8:
    docker:
      - image: circleci/python:3.8.2
    steps:
      - checkout
      - run:
          name: Python 3.8.2 CLI Test
          command: |
            python3 -V
            bash ./testing-run.sh
            bash ./regenerate-names.sh
workflows:
  version: 2
  run_all:
    jobs:
      - python3.6
      - python3.7
      - python3.8
