version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.6.9  # python 3.6
      - image: circleci/python:3.7.7  # python 3.7
      - image: circleci/python:3.8.2  # python 3.8
    steps:
      - checkout
      - store_test_results:
        path: test-results
      - run:
          name: CLI Test
          command: |
            python3 -V
            bash ./testing-run.sh
            bash ./regenerate-names.sh
      - store_artifacts:
        path: classic.txt
      - store_artifacts:
        path: random.txt