jobs:
  python36:
    docker:
      - image: circleci/python:3.6.9
    steps:
      - checkout
      - run:
          name: Python 3.6.9 CLI Test
          command: |
            python3 -V
            bash ./testing-run.sh
            bash ./regenerate-names.sh
  python37:
    docker:
      - image: circleci/python:3.7.7
    steps:
      - checkout
      - run:
          name: Python 3.7.7 CLI Test
          command: |
            python3 -V
            bash ./testing-run.sh
            bash ./regenerate-names.sh
  python38:
    docker:
      - image: circleci/python:3.8.2
    steps:
      - checkout
      - run:
          name: Python 3.8.2 CLI Test
          command: |
            python3 -V
            bash ./testing-run.sh
            bash ./regenerate-names.sh
workflows:
  version: 2
  python3.6:
    jobs:
      - python36
  python3.7:
    jobs:
      - python37
  python3.8:
    jobs:
      - python38
