version: 2.1
jobs:
  build:
    working_directory: ~/circleci-python-namegenerator
    docker:
      - image: circleci/python:3.6.9  # python 3.6
      - image: circleci/python:3.7.7  # python 3.7
      - image: circleci/python:3.8.2  # python 3.8
    steps:
      - run: bash ../testing-run.sh